A Rust rewrite based on IDesktopWallpaper Instead Of IActiveDesktop (#1)
sindresorhus/win-wallpaper pull request #9
Opened 2023-02-01 23:39 UTC by a-isaiahharvey

* reference #7

This rewrite uses the `windows` crate for using Win32 APIs and `clap` for creating the command line interface

2023-02-02 05:28 UTC, sindresorhus commented
Thanks for working on this 🙏

// @beyluta

2023-02-02 06:39 UTC, sindresorhus requested changes

2023-02-02 06:39 UTC, sindresorhus commented on src/lib.rs
> +        }
```suggestion
        let interface: IDesktopWallpaper = unsafe {
            CoInitialize(None)?;
            CoCreateInstance(&DesktopWallpaper, None, CLSCTX_LOCAL_SERVER)?;
        }
```

?

2023-02-02 06:39 UTC, sindresorhus commented on src/lib.rs
> +            let mut encoded = full_path.encode_utf16().chain([0u16]).collect::<Vec<u16>>();
Is this really the best way to convert a Path to PCWSTR?

Maybe: https://stackoverflow.com/a/74173701/64949

2023-02-02 06:39 UTC, sindresorhus commented on src/lib.rs
> +            let mut encoded = full_path.encode_utf16().chain([0u16]).collect::<Vec<u16>>();
Does this part need to be inside `unsafe`?

2023-02-02 06:39 UTC, sindresorhus commented on src/lib.rs
> +                    if path.is_dir() {
Can the if statements here be chained instead of nested?

2023-02-02 06:39 UTC, sindresorhus commented on src/lib.rs
> +        unsafe {
Can you reduce the `unsafe` usage to only the code that absolutely have to be inside the `unsafe` block?

2023-02-02 06:39 UTC, sindresorhus commented on src/lib.rs
> +                Err(_) => String::new(),
Empty string is not a good fallback. Propagate the error instead.

2023-02-02 12:41 UTC, sindresorhus requested changes

2023-02-02 12:41 UTC, sindresorhus commented on src/main.rs
> +        #[arg(short, long, default_value_t = 0)]
I was thinking maybe a `value_parser`. See: https://docs.rs/clap/latest/clap/_derive/_tutorial/index.html#validated-values

2023-02-02 12:41 UTC, sindresorhus commented on src/main.rs
> +    };
Couldn't you use `map_err` for cases like this when the value is just passed through?

2023-02-02 12:41 UTC, sindresorhus commented on src/main.rs
> +    };
I'm not familiar with `clap`. Will this cause the binary to have a non-zero exit code? If not, we should make sure all error have non-zero exit.

2023-02-02 12:41 UTC, sindresorhus commented on src/lib.rs
> +                eprintln!("{error}");
This part of the code is the library part, so for the sake of separation, I don't think it should be printing. Instead, I would make `get_wallpaper` return a Result.

2023-02-02 13:19 UTC, Turbo87 commented on src/main.rs
> +#[command(author, version, about, long_about = None)]
Example: https://github.com/rust-lang/crates.io/blob/722035b655764203ed42cd1069124144048f7d5c/src/bin/crates-admin.rs#L8-L9

2023-02-02 16:38 UTC, connor4312 commented on src/main.rs
> +    };
As-written the program will always have an exit code of 0.

2023-02-02 16:42 UTC, connor4312 commented on src/main.rs
> +}
```suggestion
fn if_chosen_monitor_within_range(choice: usize, monitors: &[Monitor], func: impl FnOnce(&Monitor)) {
    match monitors.get(choice) {
        Some(m) => func(m),
        None => eprintln!(
            "The available monitors are from 0 to {} but {choice} was given",
            monitors.len() - 1,
        ),
    }
}
```

avoids extra bounds checking when you access the index

2023-02-03 04:52 UTC, sindresorhus commented
@a-isaiahharvey Some more feedback here: https://mastodon.social/@thejpster@hachyderm.io/109797282634092665

2023-02-11 08:49 UTC, sindresorhus commented on src/main.rs
> +        #[arg(short, long, default_value_t = 0)]
I'm still a Rust noob, so I cannot help with that. Let's just add a TODO comment about it.

2023-02-11 08:53 UTC, sindresorhus requested changes

2023-02-11 08:53 UTC, sindresorhus commented on Cargo.toml
> +authors = ["Sindre Sorhus"]
@a-isaiahharvey You should add your name here. Only if you want, of course.

2023-02-11 23:40 UTC, a-isaiahharvey commented on Cargo.toml
> +authors = ["Sindre Sorhus"]
Thank you for the opportunity to be a co-author of one of your projects 😊

2023-02-12 06:44 UTC, merged

2023-02-12 06:44 UTC, sindresorhus commented
@a-isaiahharvey Great work!

2023-02-12 06:46 UTC, sindresorhus commented
@a-isaiahharvey Would you be able to compile the binary for me? Based on `main` branch: https://github.com/sindresorhus/win-wallpaper/commit/b55c6f6c20d629627d215d43836f9e8eed2547c2 (3.0.0)

2023-02-12 08:05 UTC, a-isaiahharvey commented
[wallpaper-aarch64-pc-windows-msvc.zip](https://github.com/sindresorhus/win-wallpaper/files/10715591/wallpaper-aarch64-pc-windows-msvc.zip)
[wallpaper-x86_64-pc-windows-msvc.zip](https://github.com/sindresorhus/win-wallpaper/files/10715592/wallpaper-x86_64-pc-windows-msvc.zip)

2023-02-12 08:07 UTC, a-isaiahharvey commented
@sindresorhus Here are the compiled binaries 
[wallpaper-aarch64-pc-windows-msvc.zip](https://github.com/sindresorhus/win-wallpaper/files/10715599/wallpaper-aarch64-pc-windows-msvc.zip)
[wallpaper-x86_64-pc-windows-msvc.zip](https://github.com/sindresorhus/win-wallpaper/files/10715600/wallpaper-x86_64-pc-windows-msvc.zip)

2023-02-12 09:05 UTC, sindresorhus commented
https://github.com/sindresorhus/win-wallpaper/releases/tag/v3.0.0